aliases:
  - &restore_gradle_cache
    run:
      command: echo "restore_gradle_cache"

  - &restore_robolectric_cache
    run:
      command: echo "restore_robolectric_cache"

  - &restore_bundle_cache
    run:
      command: echo "restore_bundle_cache"

  - &environment
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha

version: 2
workflows:
  version: 2
  "Build Pipeline":
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - tests:
          requires:
            - dependencies
      - upload_app_metrics_manifest:
          requires:
            - tests
            - lint

jobs:
  dependencies:
    <<: *environment
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_robolectric_cache
      - *restore_bundle_cache
      - run:
          name: Bundle install
          command: echo "Done"


  lint:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - *restore_gradle_cache
      - run:
          name: Run checkStyle, pmd and lint
          command: echo "Done"

  tests:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - *restore_gradle_cache
      - *restore_robolectric_cache
      - run:
          name: Run tests
          command: echo "Done"
      - run:
          name: test splitting output
          command: |
            # Get list of classnames of tests that should run on this node
            pwd
            ls
            cd app
            cd src/test/java
            CLASSNAMES=$(circleci tests glob "**/*Test.*" \
              | cut -c 1- | sed 's@/@.@g' \
              | sed 's/\.[^.]*$//' \
              | circleci tests split --total=2 --split-by=timings --timings-type=classname)
            cd ./../../../..
            # Format the arguments to "./gradlew test"
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            echo testIndiaReleaseUnitTest $GRADLE_ARGS


  upload_app_metrics_manifest:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Danger
          command: bundle exec danger --dangerfile=danger/Dangerfile --verbose
