aliases:
  - &restore_gradle_cache
    run:
      command: echo "restore_gradle_cache"

  - &restore_robolectric_cache
    run:
      command: echo "restore_robolectric_cache"

  - &restore_bundle_cache
    restore_cache:
      name: Restoring bundle cache
      key: bundle-{{ checksum "Gemfile.lock" }}

  - &save_bundle_cache
    save_cache:
      name: Save bundle cache
      paths:
        - vendor/bundle
      key: bundle-{{ checksum "Gemfile.lock" }}

  - &environment
    docker:
      - image: cimg/base:2020.01
    environment:
      TERM: xterm

version: 2
workflows:
  version: 2
  "Build Pipeline":
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - tests:
          requires:
            - dependencies

jobs:
  dependencies:
    <<: *environment
    steps:
      - checkout
      - *restore_gradle_cache
      - *restore_robolectric_cache
      - *restore_bundle_cache
      - run:
          name: Git command
          command: git fetch origin master && echo $(git diff --shortstat master)
      - run:
          name: Check commands
          command: ls -la

  lint:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - *restore_gradle_cache
      - run:
          name: Run checkStyle, pmd and lint
          command: echo "Done"

  tests:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - *restore_gradle_cache
      - *restore_robolectric_cache
      - run:
          name: Run tests
          command: echo "Done"


  upload_app_metrics_manifest:
    <<: *environment
    steps:
      - attach_workspace:
          at: .
      - *restore_bundle_cache
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - *save_bundle_cache
      - run:
          name: Execute Danger
          command: bundle exec danger --dangerfile=danger/Dangerfile --verbose
