version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check docker images
          command: docker images
#    working_directory: ~/code
#    docker:
#      - image: circleci/android:api-28-alpha
#    resource_class: large
#    steps:
#      - checkout
#      - restore_cache:
#          key: supply-{{ checksum ".circleci/config.yml" }}
#      - save_cache:
#          paths:
#            - "~/.gradle"
#          key: supply-{{ checksum ".circleci/config.yml" }}
#      - run:
#          name: Run tests
#          command: echo "Test cases ran"
