restore_cache1: &restore_cache1
- run:
    command: echo "Restoring cache1"

restore_cache2: &restore_cache2
- run:
    command: echo "Restoring cache2"

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - *restore_cache1
      - *restore_cache2
      - run:
          command: echo "Test completed"
