version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: supply-{{ checksum ".circleci/config.yml" }}
      - save_cache:
          paths:
            - "~/.gradle"
          key: supply-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run tests
          command: echo "Test cases ran"
